### ISSUE TITLE
Continue project

### ISSUE THREAD

**Issue by Mecanik** [JKornev/DLib-Attacher#1]
Hi,

Are you willing to continue updating this project ? I`m willing to help.

Thanks

**Comment by Mecanik** [comment]
It's surprising to see that it still works today... and would be amazing to continue it. There are not many attachers out there for TLS :)

**Comment by JKornev** [comment]
Hi,

I think I'm not going to continue a project. Because it's open source you are free to add or change whatever you want.

Regards,
JK
